[package]
name = "pyastrs"
version = "0.0.1"
authors = ["Matthew Planchard <msplanchard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "~6.1.0"
rowan = "~0.12.1"
